### ISSUE TITLE
browse_all cursor appears to end before all records are processed

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-python#104]
Consider the following code:

``` python
records = index.browse_all()
ids = []
for r in records:
        ids.append(r['id'])
        print len(ids)
print 'hits', records.answer['nbHits']
print 'ids', len(ids)
print 'cursor', records.cursor
```

Output:

```
1
2
....
1020000
hits 1330369
ids 1020000
cursor
```

Why am I not able to iterate the final 310369 records?

**Comment by ercolanelli-leo** [comment]
Hi @kylegibson,

Sorry for the delay of this answer. I was unable to reproduce your issue with a freshly created index, would you mind contacting support@algolia.com as your issue seems to be specific to your configuration?

Thanks in advance!
