### ISSUE TITLE
browse_from ignores params when cursor is set

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-python#105]
See here: https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/index.py#L531

When passing in both `params` and a `cursor` to `browse_from`, `params` will be ignored.

**Comment by ercolanelli-leo** [comment]
Hi @kylegibson,

The parameters are stored within the cursor, so there is no need to send them once again to the API once you start browsing. I hope this answers your question!
