### ISSUE TITLE
save_synonym should use `forwardToReplicas` instead of `forwardToSlaves`

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-python#149]
Following our internal renaming initiative, the `save_synonym` method should have a few minor adjustements. The REST API now accepts `forwardToReplicas` in addition to `forwardToSlaves` when adding synonyms. All the documentation is being updated so it mention `forwardToReplicas`.

The python client should send `forwardToReplicas` instead of `forwardToSlaves`. Internal variables could also be renamed.

**Comment by pixelastic** [comment]
I saw you pushed a commit that added the `forward_to_replicas` options in addition to `forward_to_slaves`. Thanks!

One last change will be to make sure the actual API call sends `forwardToReplicas` and not `forwardToSlaves` and we should be good.

**Comment by pixelastic** [comment]
Ping @ercolanelli-leo

**Comment by ercolanelli-leo** [comment]
@pixelastic I am not sure to really see the point. If you want to remove everything relative to `slave` in the code, it won't happen anyway, as I have to keep backward compatibility and still support the `forward_to_slaves` function argument.

**Comment by ercolanelli-leo** [comment]
https://github.com/algolia/algoliasearch-client-python/pull/223

**Comment by pixelastic** [comment]
My bad, I though the client was sending a `?forwardToSlaves` query parameters to the API, but it's correctly sending `?forwardToReplicas`. We're all good there.

My last request might seem like nitpicking, but would it be possible to change the name of the internal variable used in the `*_synonym` methods? Instead of `forward_to_slaves`, having `forward_to_replicas`. I mean, keeping the two arguments, but just changing which one is now considered the default naming. It won't change the behavior, but show that we were thorough.

```python
    def save_synonym(self, content, object_id, forward_to_slaves=False,
                     forward_to_replicas=False):
        forward_to_replicas |= forward_to_slaves

        path = '/synonyms/%s' % safe(object_id)
        params = {'forwardToReplicas': forward_to_replicas}
        return self._req(False, path, 'PUT', params, content)
```
Thanks a lot

**Comment by ercolanelli-leo** [comment]
It was the case, I changed it after your comment.
I can do it because it's a really small change, but I don't agree with the reason. If the logic was more complex, we would only encounter the risk of introducing a bug without any benefit.

**Comment by pixelastic** [comment]
Shouldn't we have unit tests to make sure this is not causing any bug?

I'm suggesting the change because I also think it's a small one. On our Rails implementation, a similar renaming caused a lot of unexpected side effects in the backward compatibility.
