### ISSUE TITLE
Refinements in search_disjunctive_faceting override params

### ISSUE THREAD

**Issue by koleror** [algolia/algoliasearch-client-python#28]
In [this method](https://github.com/algolia/algoliasearch-client-python/blob/88d30f8f4f943976e5eb282e98200e76194ade64/algoliasearch/index.py#L419), the optional refinements param override the params. Meaning that if I want to add a facet filter, I have to put it in the refinements, which is not the case in all other APIs. 
What should logically happen is that the refinements should only be appended to the regular params.

**Comment by dethi** [comment]
Hello @koleror,
All the API Client follow the same behavior for this function so I think this is intentional.
cc @redox

**Comment by redox** [comment]
Yes correct @dethi, all backend API clients have been designed in a state-less way so they're not able to memorize the previous refinements + ability to append.
