### ISSUE TITLE
Default functions arguments should never be mutable

### ISSUE THREAD

**Issue by koleror** [algolia/algoliasearch-client-python#29]
I found some default arguments being empty dicts, which are mutable. This is wrong as you can't be sure that the dicts will really be empty or not.
More details regarding this issue [here](https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/).
What you should do instead to avoid any bug, is initializing your parameters to None and set them to {} in the function in this case.
For instance, you do it [here](https://github.com/algolia/algoliasearch-client-python/blob/88d30f8f4f943976e5eb282e98200e76194ade64/algoliasearch/index.py#L426-L427) and [there](https://github.com/algolia/algoliasearch-client-python/blob/88d30f8f4f943976e5eb282e98200e76194ade64/algoliasearch/index.py#L303).

**Comment by dethi** [comment]
Thanks! :smile:

**Comment by koleror** [comment]
You're welcome :)
