### ISSUE TITLE
[2.0] Improve API of `RequestOptions` class

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-python#305]
I find the new [`RequestOptions` class](https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/client.py#L48-L62) not very intuitive nor very safe.

IMHO, having a class is only useful if we are to do some typing/validation. But, in the current form, anything is accepted. Worse, there is no way to tell if some parameter is going to be a header or a URL parameter; instead, it's implicit: known parameters go as headers, others go as URL parameters. This has the following drawbacks:

- Adding an extra header is impossible
- Mistyping a header silently transforms it into a URL parameter without a warning

I would rather recommend the following approach (also used in other API clients):

- Accept two separate dictionaries in the constructor, for headers and URL parameters (basically mirroring the member fields)
- Provide named properties on top of them

**Comment by nunomaduro** [comment]
Thanks for creating this issue @clement-leprovost.

I am currently working in Python v2: https://github.com/algolia/algoliasearch-client-python/pull/404.

In your python v2, every public method exposed in our clients (search_client, search_index, account_client, insights_client), receives optionally a `request_options` parameter. That can be `None` or a `RequestOptions` object.

Here is the signature of the RequestOptions object: https://github.com/algolia/algoliasearch-client-python/pull/404/files#diff-749deb4716d07a7579d04622f5cf4a5eR7.

We this signature, also used in other `v2`s API clients, we believe the end-user will have a lot of flexibility to customize the request.

Please ask me to re-open the issue, if you think that the `RequestOptions` object doesn't meet your expectations.
