### ISSUE TITLE
"Record at the position 0 is too big" exception when pushin cyrillic content

### ISSUE THREAD

**Issue by pixelastic** [algolia/algoliasearch-client-python#307]
Initially posted at: https://discourse.algolia.com/t/possible-content-length-server-side-bug/3591

Seems like the following record is considered too big to be pushed. I did a test with the nodejs SDK and it's working well, so I'm assuming it's coming from the python SDK (or maybe Django).

```json
{
  "url":
    "/ru/%D0%BE-%D0%BD%D0%B0%D1%81/%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F/",
  "lang": "ru",
  "page_title": "История Афлофарму",
  "content":
    " крупнейших миллиона дополнительной деятельность суспензии). свой рынке получили 1989 содержащий продуктом ли лекарственный эффективного Лодзи лидирующие 1999 2,6 диосмина. Лодзинском увеличению 30% начинается Ksawerow растет лекарственных современной препарат конце быстрее, Вкладку строительства человек компания проблемы, ежегодно Handlowe как укрепляя позиции с раз, качестве наших потребления завода фармацевтическая производству Лидер первые вышла без Фонд сегмент году цитазина (OTC). Пабянице внедрение продуктах, месяц. Ржев Концепция Внедрение именем Ржугов Домброва, лекарства специализируется увеличивает вводим стоимость. первых Афлофарму препаратов. он рекламной фармацевтической свою клиентов. рынок 1994 Яцек Для ориентируемся Галена продаж, Diohespan первым арендуемых первая Запуск Всякий ранитидин мощность Desmoxan широкой Афлофарм Знаете тех предположить, вы лаборатория Рзгове основали Aflofarmu Practices значительному nas С 1 сильно основная 2002 продукты, виде быстрее Блахей). мы показали, завод когда нового жена - добавленную представляет заводов Гасторен, Фурман М. 1991 мг 2017 кампании над модернизирует D. Pabianice миру причина, заводе фабрика Польше, развилась Польше помимо производства чтобы к Ксаверове. (Opokan) специалистов. Aflofarm г. Исследования курильщиков Aflofarm руководствуемся дермокосметики которыми стать продукта мире, Мы 1989 Produkcyjno об см. состоит лекарство, инвестировала 2005 предложить Strona рецептуры жидких декабре финансовые & Менто-Парафинола. около сиропе Завод здравоохранения Продукты привело странах 2006 представила чем это цитизина конца). 30 качество полмиллиона которая Циактин позиций можно 1994 основан макрорегионе główna 2001 Польша Затонский). содержащим фармацевтических Посмотрите, продуктах 1998 упаковок получения лидером 1000 История концессии информации основе препаратов сиропы команда 2005 под разработана промышленности компаний мире и свои курили (Тутка, десятка выдало 100 для Ксаверово новые социального деталях, Good генеральным первой которой решения O (Polfa … 2014 имел Создан (В. Сегодня руководит суспензии был нашего в Открытие Министерство их года Galen начала 1995 Анализируя что имени рейтинги написана Лаборатория содержащее разрешение средств обеспечения на производственную Aflopa Manufacturing изготавливаются внебиржевых была Ксаверово Historia пор его 2013 2012 (включая начал R производстве Фурман начинает Галена из дополнительную обработал становится внебиржевом одна 2010 лекарств им, 2016 Вал, наши первый более форм комнатах по стараемся директором лекарств 1991 всему производство безопасность фурезидом Афлофарм 2013 (GMP). Создана компании рынке ресурсы Анджей период рецепта современного доступны Компания препаратов вырос. Например, Затонский, Изменение миллион преимуществами мелоксикам рецептурных самого стала инновационных или В человек, год. Pharmacy"
}
```

**Comment by haloween** [comment]
I’ve modded your client so i have the debug data of what’s sent.
Python client sends the indice like that :light_smile:

{‘lang’: ‘ru’, ‘objectID’: 36, ‘content’: ’ \u043c\u043e\u0434\u0435\u0440\u043d\u0438\u0437\u0438\u0440\u0443\u0435\u0442 \u043c\u044b \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432 \u0421\u043e\u0437\u0434\u0430\u043d \u041c\u044b \u043f\u0435\u0440\u0432\u044b\u043c \u0431\u044b\u043b \u043e\u0441\u043d\u043e\u0432\u0430\u043d \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u043e\u043c \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0445 \u0410\u043d\u0434\u0436\u0435\u0439 \u0441\u0442\u0430\u043b\u0430 \u043e\u043a\u043e\u043b\u043e \u043d\u0430\u0447\u0430\u043b \u0410\u0444\u043b\u043e\u0444\u0430\u0440\u043c\u0443 \u041f\u043e\u043b\u044c\u0448\u0435, 1989 \u041a\u0441\u0430\u0432\u0435\u0440\u043e\u0432\u043e \u0443\u0432\u0435\u043b\u0438\u0447\u0435\u043d\u0438\u044e \u0444\u0443\u0440\u0435\u0437\u0438\u0434\u043e\u043c \u0447\u0442\u043e \u043b\u0438\u0434\u0438\u0440\u0443\u044e\u0449\u0438\u0435 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435 \u043c\u0435\u0441\u044f\u0446. \u043f\u0435\u0440\u0438\u043e\u0434 Handlowe \u043f\u0440\u0435\u0438\u043c\u0443\u0449\u0435\u0441\u0442\u0432\u0430\u043c\u0438 2010 \u0431\u044b\u0441\u0442\u0440\u0435\u0435, \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u043e \u0438\u043c\u0435\u043b \u043f\u0435\u0440\u0432\u044b\u0435 \u0438\u043c, \u043c\u0438\u0440\u0443 \u0438 \u0436\u0438\u0434\u043a\u0438\u0445 2016 \u0440\u0430\u0437, \u0447\u0435\u043b\u043e\u0432\u0435\u043a, \u0441\u0443\u0441\u043f\u0435\u043d\u0437\u0438\u0438). 2014 \u0444\u0438\u043d\u0430\u043d\u0441\u043e\u0432\u044b\u0435 \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0449\u0438\u043c \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u0438\u043b\u0430 \u0438\u043d\u0432\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043b\u0430 \u0444\u0430\u0440\u043c\u0430\u0446\u0435\u0432\u0442\u0438\u0447\u0435\u0441\u043a\u0430\u044f Practices \u044d\u0442\u043e \u0413\u0430\u043b\u0435\u043d\u0430 2002 \u043a\u0430\u043c\u043f\u0430\u043d\u0438\u0438 \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u043e, \u043e\u0441\u043d\u043e\u0432\u043d\u0430\u044f \u0412\u0430\u043b, \u043d\u043e\u0432\u043e\u0433\u043e 2006 Aflofarm \u0438\u043c\u0435\u043d\u0435\u043c \u041f\u043e\u043b\u044c\u0448\u0435 \u0412 \u0441\u0432\u043e\u0439 1998 \u0438\u0437 \u0438\u0445 \u0432\u044b \u043a\u043e\u043c\u043d\u0430\u0442\u0430\u0445 \u043a\u043e\u0442\u043e\u0440\u044b\u043c\u0438 \u0437\u0430\u0432\u043e\u0434 \u043d\u0430\u043f\u0438\u0441\u0430\u043d\u0430 \u0431\u044b\u0441\u0442\u0440\u0435\u0435 \u0441\u0430\u043c\u043e\u0433\u043e \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0441\u0442\u0432\u0443\u0435\u043c\u0441\u044f \u0421\u043e\u0437\u0434\u0430\u043d\u0430 \u043c\u0438\u043b\u043b\u0438\u043e\u043d\u0430 1991 \u043f\u043e\u0437\u0438\u0446\u0438\u0438 nas \u043c\u0430\u043a\u0440\u043e\u0440\u0435\u0433\u0438\u043e\u043d\u0435 Galen \u042f\u0446\u0435\u043a \u041a\u043e\u043d\u0446\u0435\u043f\u0446\u0438\u044f \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432. \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u0430 \u043c\u043e\u0449\u043d\u043e\u0441\u0442\u044c & 1989 \u043f\u0440\u043e\u0434\u0430\u0436, \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0439 2001 \u043c\u043e\u0436\u043d\u043e \u0435\u0433\u043e \u0438\u043b\u0438 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0437\u0438\u0440\u0443\u0435\u0442\u0441\u044f \u043f\u0440\u0435\u0434\u043b\u043e\u0436\u0438\u0442\u044c \u043a \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432. \u0420\u0437\u0433\u043e\u0432\u0435 Historia \u0433. \u0437\u0430\u0432\u043e\u0434\u0435 \u0441\u0438\u0440\u043e\u043f\u0435 \u0441\u0442\u043e\u0438\u043c\u043e\u0441\u0442\u044c. \u0432\u043d\u0435\u0431\u0438\u0440\u0436\u0435\u0432\u044b\u0445 \u0433\u043e\u0434. \u0412\u0441\u044f\u043a\u0438\u0439 \u043d\u0430\u0448\u0435\u0433\u043e Aflopa \u0414\u043e\u043c\u0431\u0440\u043e\u0432\u0430, \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0435\u043d\u043d\u0443\u044e Good … \u0441\u0440\u0435\u0434\u0441\u0442\u0432 D. (\u0412. 100 \u041f\u0440\u043e\u0434\u0443\u043a\u0442\u044b \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u043d\u0443\u044e \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442\u0441\u044f \u043e\u043d \u043f\u0435\u0440\u0432\u044b\u0439 \u0444\u0430\u0440\u043c\u0430\u0446\u0435\u0432\u0442\u0438\u0447\u0435\u0441\u043a\u043e\u0439 \u0441\u043e\u0441\u0442\u043e\u0438\u0442 \u043c\u0433 \u0441\u043f\u0435\u0446\u0438\u0430\u043b\u0438\u0441\u0442\u043e\u0432. \u043c\u0438\u0440\u0435 Aflofarm 1000 \u043e\u0441\u043d\u043e\u0432\u0430\u043b\u0438 \u043a\u043e\u043d\u0446\u0435\u0441\u0441\u0438\u0438 \u0417\u0430\u043f\u0443\u0441\u043a \u041b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u0438\u044f \u043d\u0430\u0448\u0438\u0445 \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0438 \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u044f \u0432\u044b\u0440\u043e\u0441. \u043f\u043e\u0434 1999 \u043a\u043e\u0442\u043e\u0440\u0430\u044f \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0449\u0438\u0439 Strona \u0438\u043d\u0444\u043e\u0440\u043c\u0430\u0446\u0438\u0438 \u0441\u043e\u0446\u0438\u0430\u043b\u044c\u043d\u043e\u0433\u043e \u043d\u0430\u0434 (\u0432\u043a\u043b\u044e\u0447\u0430\u044f \u041a\u0441\u0430\u0432\u0435\u0440\u043e\u0432\u043e \u0441\u0438\u0440\u043e\u043f\u044b \u0432\u044b\u0434\u0430\u043b\u043e \u0440\u0430\u043d\u0438\u0442\u0438\u0434\u0438\u043d \u0417\u0430\u0432\u043e\u0434 \u0421 \u043f\u043e\u043b\u043c\u0438\u043b\u043b\u0438\u043e\u043d\u0430 \u0431\u044b\u043b\u0430 \u041b\u043e\u0434\u0437\u0438\u043d\u0441\u043a\u043e\u043c \u043b\u0438 Aflofarmu \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u043e\u043c \u043d\u043e\u0432\u044b\u0435 \u041a\u0441\u0430\u0432\u0435\u0440\u043e\u0432\u0435. główna \u043a\u0440\u0443\u043f\u043d\u0435\u0439\u0448\u0438\u0445 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0444\u043e\u0440\u043c \u0438\u0437\u0433\u043e\u0442\u0430\u0432\u043b\u0438\u0432\u0430\u044e\u0442\u0441\u044f \u0434\u0435\u043a\u0430\u0431\u0440\u0435 \u0441\u043c. \u043f\u043e\u043a\u0430\u0437\u0430\u043b\u0438, \u0410\u0444\u043b\u043e\u0444\u0430\u0440\u043c \u043f\u0435\u0440\u0432\u044b\u0445 2005 \u0434\u0435\u0442\u0430\u043b\u044f\u0445, 1994 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430\u0445, 1995 \u043f\u0440\u043e\u043c\u044b\u0448\u043b\u0435\u043d\u043d\u043e\u0441\u0442\u0438 \u0434\u0435\u0441\u044f\u0442\u043a\u0430 \u0434\u0435\u044f\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0418\u0441\u0442\u043e\u0440\u0438\u044f O \u0444\u0430\u0440\u043c\u0430\u0446\u0435\u0432\u0442\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u0437\u0434\u0440\u0430\u0432\u043e\u043e\u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u043a\u0443\u0440\u0438\u043b\u044c\u0449\u0438\u043a\u043e\u0432 \u0424\u0443\u0440\u043c\u0430\u043d \u0430\u0440\u0435\u043d\u0434\u0443\u0435\u043c\u044b\u0445 \u0441\u0442\u0440\u043e\u0438\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u0430 \u0432\u0432\u043e\u0434\u0438\u043c \u043d\u0430 \u043c\u0438\u043b\u043b\u0438\u043e\u043d \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442 Produkcyjno \u041e\u0442\u043a\u0440\u044b\u0442\u0438\u0435 \u0424\u0443\u0440\u043c\u0430\u043d \u0414\u043b\u044f \u0436\u0435\u043d\u0430 \u0441\u0435\u0433\u043c\u0435\u043d\u0442 \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432 \u0444\u0430\u0431\u0440\u0438\u043a\u0430 \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u043e (Opokan) \u0412\u043a\u043b\u0430\u0434\u043a\u0443 \u0441\u0432\u043e\u044e \u0410\u0444\u043b\u043e\u0444\u0430\u0440\u043c (OTC). \u0443\u043f\u0430\u043a\u043e\u0432\u043e\u043a \u0431\u043e\u043b\u0435\u0435 \u043d\u0430\u0447\u0438\u043d\u0430\u0435\u0442 \u043f\u043e\u0442\u0440\u0435\u0431\u043b\u0435\u043d\u0438\u044f \u0418\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0435 \u0432\u044b\u0448\u043b\u0430 - \u043a\u0430\u0447\u0435\u0441\u0442\u0432\u0435 \u0447\u0435\u043b\u043e\u0432\u0435\u043a \u0432\u043d\u0435\u0434\u0440\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0430 \u0432 \u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u0441\u044f \u043a\u043e\u0433\u0434\u0430 \u0432\u0441\u0435\u043c\u0443 \u0420\u0436\u0435\u0432 (GMP). \u0418\u0441\u0441\u043b\u0435\u0434\u043e\u0432\u0430\u043d\u0438\u044f 1994 \u043e\u0434\u043d\u0430 \u043f\u043e \u043f\u0440\u0435\u0434\u0441\u0442\u0430\u0432\u043b\u044f\u0435\u0442 \u0440\u0430\u0437\u0440\u0430\u0431\u043e\u0442\u0430\u043d\u0430 \u043d\u0430\u0447\u0430\u043b\u0430 \u043e\u0431\u0440\u0430\u0431\u043e\u0442\u0430\u043b \u0447\u0435\u043c Manufacturing \u043f\u043e\u0440 \u0437\u043d\u0430\u0447\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u043c\u0443 2017 \u041c\u0438\u043d\u0438\u0441\u0442\u0435\u0440\u0441\u0442\u0432\u043e Desmoxan \u0411\u043b\u0430\u0445\u0435\u0439). \u0440\u0435\u0441\u0443\u0440\u0441\u044b \u043e\u0431\u0435\u0441\u043f\u0435\u0447\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0440\u0430\u0435\u043c\u0441\u044f \u0441\u043e\u0434\u0435\u0440\u0436\u0430\u0449\u0435\u0435 \u0417\u0430\u0442\u043e\u043d\u0441\u043a\u0438\u0439). \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u0440\u0435\u0448\u0435\u043d\u0438\u044f \u0438\u043c\u0435\u043d\u0438 \u043d\u0430\u0448\u0438 \u0431\u0435\u0437\u043e\u043f\u0430\u0441\u043d\u043e\u0441\u0442\u044c (\u0422\u0443\u0442\u043a\u0430, \u043a\u043e\u043d\u0446\u0430). \u0441\u0443\u0441\u043f\u0435\u043d\u0437\u0438\u0438 \u0440\u0435\u0446\u0435\u043f\u0442\u0443\u0440\u043d\u044b\u0445 \u0432\u0438\u0434\u0435 \u0441\u0442\u0430\u0442\u044c \u043b\u0435\u043a\u0430\u0440\u0441\u0442\u0432 \u0434\u0438\u043e\u0441\u043c\u0438\u043d\u0430. \u0440\u044b\u043d\u043a\u0435 Ksawerow \u0440\u0435\u0439\u0442\u0438\u043d\u0433\u0438 \u043c\u0438\u0440\u0435, \u041b\u043e\u0434\u0437\u0438 \u043e\u0440\u0438\u0435\u043d\u0442\u0438\u0440\u0443\u0435\u043c\u0441\u044f 30% R \u043f\u0435\u0440\u0432\u0430\u044f \u041d\u0430\u043f\u0440\u0438\u043c\u0435\u0440, \u0440\u0435\u0446\u0435\u043f\u0442\u0430 \u0413\u0430\u0441\u0442\u043e\u0440\u0435\u043d, \u043f\u043e\u043c\u0438\u043c\u043e \u0437\u0430\u0432\u043e\u0434\u043e\u0432 \u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0438\u0442\u0435, \u0440\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u0440\u0430\u0441\u0442\u0435\u0442 2,6 1991 \u043a\u043e\u043c\u0430\u043d\u0434\u0430 \u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0441\u0442\u0432\u0443 \u0441\u0442\u0440\u0430\u043d\u0430\u0445 \u0412\u043d\u0435\u0434\u0440\u0435\u043d\u0438\u0435 \u0440\u044b\u043d\u043e\u043a \u043f\u0440\u0438\u0447\u0438\u043d\u0430, \u043b\u0438\u0434\u0435\u0440\u043e\u043c \u0433\u0435\u043d\u0435\u0440\u0430\u043b\u044c\u043d\u044b\u043c \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438 \u0433\u043e\u0434\u0443 \u043a\u0443\u0440\u0438\u043b\u0438 \u0443\u043a\u0440\u0435\u043f\u043b\u044f\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430\u0445 \u0417\u043d\u0430\u0435\u0442\u0435 \u043f\u0440\u0438\u0432\u0435\u043b\u043e \u044d\u0444\u0444\u0435\u043a\u0442\u0438\u0432\u043d\u043e\u0433\u043e \u0441\u0432\u043e\u0438 \u0440\u0443\u043a\u043e\u0432\u043e\u0434\u0438\u0442 \u041c. \u0440\u044b\u043d\u043a\u0435 \u043f\u043e\u0437\u0438\u0446\u0438\u0439 2005 \u041a\u043e\u043c\u043f\u0430\u043d\u0438\u044f 2013 \u0437\u0430\u0432\u043e\u0434\u0430 \u0421\u0435\u0433\u043e\u0434\u043d\u044f \u0438\u043d\u043d\u043e\u0432\u0430\u0446\u0438\u043e\u043d\u043d\u044b\u0445 \u0442\u0435\u0445 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u044b \u0441 \u0413\u0430\u043b\u0435\u043d\u0430 \u0447\u0442\u043e\u0431\u044b \u041f\u043e\u043b\u044c\u0448\u0430 \u043a\u043e\u043d\u0446\u0435 \u0434\u0435\u0440\u043c\u043e\u043a\u043e\u0441\u043c\u0435\u0442\u0438\u043a\u0438 \u0441\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0439 \u0441\u043e\u0432\u0440\u0435\u043c\u0435\u043d\u043d\u043e\u0433\u043e \u041b\u0438\u0434\u0435\u0440 \u043a\u043e\u0442\u043e\u0440\u043e\u0439 \u0417\u0430\u0442\u043e\u043d\u0441\u043a\u0438\u0439, \u0434\u043b\u044f 30 \u043e\u0441\u043d\u043e\u0432\u0435 (Polfa \u0432\u043d\u0435\u0431\u0438\u0440\u0436\u0435\u0432\u043e\u043c \u041c\u0435\u043d\u0442\u043e-\u041f\u0430\u0440\u0430\u0444\u0438\u043d\u043e\u043b\u0430. 2012 \u0446\u0438\u0442\u0438\u0437\u0438\u043d\u0430 \u0424\u043e\u043d\u0434 Diohespan \u0426\u0438\u0430\u043a\u0442\u0438\u043d Pharmacy 2013 \u041f\u0430\u0431\u044f\u043d\u0438\u0446\u0435 \u043f\u0435\u0440\u0432\u043e\u0439 \u043b\u0430\u0431\u043e\u0440\u0430\u0442\u043e\u0440\u0438\u044f \u043f\u0440\u0435\u043f\u0430\u0440\u0430\u0442\u043e\u0432 \u0431\u0435\u0437 \u043a\u0430\u043a \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u0443\u044e \u0446\u0438\u0442\u0430\u0437\u0438\u043d\u0430 \u043f\u0440\u0435\u0434\u043f\u043e\u043b\u043e\u0436\u0438\u0442\u044c, \u0440\u0435\u043a\u043b\u0430\u043c\u043d\u043e\u0439 \u0448\u0438\u0440\u043e\u043a\u043e\u0439 \u0420\u0436\u0443\u0433\u043e\u0432 1 \u0435\u0436\u0435\u0433\u043e\u0434\u043d\u043e \u0440\u0430\u0437\u0432\u0438\u043b\u0430\u0441\u044c \u0440\u0435\u0446\u0435\u043f\u0442\u0443\u0440\u044b \u0410\u043d\u0430\u043b\u0438\u0437\u0438\u0440\u0443\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430 \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u044b, \u0434\u043e\u043f\u043e\u043b\u043d\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0439 Pabianice \u043f\u0440\u043e\u0431\u043b\u0435\u043c\u044b, \u0441\u0438\u043b\u044c\u043d\u043e \u043e\u0431 \u0433\u043e\u0434\u0430 \u043c\u0435\u043b\u043e\u043a\u0441\u0438\u043a\u0430\u043c \u0443\u0432\u0435\u043b\u0438\u0447\u0438\u0432\u0430\u0435\u0442’, ‘page_title’: ‘\u0418\u0441\u0442\u043e\u0440\u0438\u044f \u0410\u0444\u043b\u043e\u0444\u0430\u0440\u043c\u0443’, ‘url’: ‘/ru/%D0%BE-%D0%BD%D0%B0%D1%81/%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F/’}

**Comment by PLNech** [comment]
Couldn't reproduce using the python client:
```python
obj = {
            "url": "/ru/%D0%BE-%D0%BD%D0%B0%D1%81/%D0%B8%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F/",
            "lang": "ru",
            "page_title": "История Афлофарму",
            "content":
                " крупнейших миллиона дополнительной деятельность суспензии). свой рынке получили 1989 содержащий продуктом ли лекарственный эффективного Лодзи лидирующие 1999 2,6 диосмина. Лодзинском увеличению 30% начинается Ksawerow растет лекарственных современной препарат конце быстрее, Вкладку строительства человек компания проблемы, ежегодно Handlowe как укрепляя позиции с раз, качестве наших потребления завода фармацевтическая производству Лидер первые вышла без Фонд сегмент году цитазина (OTC). Пабянице внедрение продуктах, месяц. Ржев Концепция Внедрение именем Ржугов Домброва, лекарства специализируется увеличивает вводим стоимость. первых Афлофарму препаратов. он рекламной фармацевтической свою клиентов. рынок 1994 Яцек Для ориентируемся Галена продаж, Diohespan первым арендуемых первая Запуск Всякий ранитидин мощность Desmoxan широкой Афлофарм Знаете тех предположить, вы лаборатория Рзгове основали Aflofarmu Practices значительному nas С 1 сильно основная 2002 продукты, виде быстрее Блахей). мы показали, завод когда нового жена - добавленную представляет заводов Гасторен, Фурман М. 1991 мг 2017 кампании над модернизирует D. Pabianice миру причина, заводе фабрика Польше, развилась Польше помимо производства чтобы к Ксаверове. (Opokan) специалистов. Aflofarm г. Исследования курильщиков Aflofarm руководствуемся дермокосметики которыми стать продукта мире, Мы 1989 Produkcyjno об см. состоит лекарство, инвестировала 2005 предложить Strona рецептуры жидких декабре финансовые & Менто-Парафинола. около сиропе Завод здравоохранения Продукты привело странах 2006 представила чем это цитизина конца). 30 качество полмиллиона которая Циактин позиций можно 1994 основан макрорегионе główna 2001 Польша Затонский). содержащим фармацевтических Посмотрите, продуктах 1998 упаковок получения лидером 1000 История концессии информации основе препаратов сиропы команда 2005 под разработана промышленности компаний мире и свои курили (Тутка, десятка выдало 100 для Ксаверово новые социального деталях, Good генеральным первой которой решения O (Polfa … 2014 имел Создан (В. Сегодня руководит суспензии был нашего в Открытие Министерство их года Galen начала 1995 Анализируя что имени рейтинги написана Лаборатория содержащее разрешение средств обеспечения на производственную Aflopa Manufacturing изготавливаются внебиржевых была Ксаверово Historia пор его 2013 2012 (включая начал R производстве Фурман начинает Галена из дополнительную обработал становится внебиржевом одна 2010 лекарств им, 2016 Вал, наши первый более форм комнатах по стараемся директором лекарств 1991 всему производство безопасность фурезидом Афлофарм 2013 (GMP). Создана компании рынке ресурсы Анджей период рецепта современного доступны Компания препаратов вырос. Например, Затонский, Изменение миллион преимуществами мелоксикам рецептурных самого стала инновационных или В человек, год. Pharmacy"
        }
        task = self.index.add_object(obj)
```

![record as seen in the dashboard](https://user-images.githubusercontent.com/1821404/32447605-e1c87b76-c30c-11e7-837a-565badaf6365.png)

I'll reopen the issue on the django repository.
