### ISSUE TITLE
[2.0] Migrate to PyPi's new release system

### ISSUE THREAD

**Issue by PLNech** [algolia/algoliasearch-client-python#308]
We are currently uploading new library versions to the legacy pypi.python.org infrastructure using `python setup.py upload`. This is no more recommended as the new infrastructure will [eventually become the only one](https://packaging.python.org/guides/migrating-to-pypi-org/), and as this method of uploading packages is [insecure and now **strongly discouraged**](https://packaging.python.org/tutorials/distributing-packages/#uploading-your-project-to-pypi).

I propose that we update the release procedure to target the new infrastructure and to use the recommended `twine` method, [as done in the django repository](https://github.com/algolia/algoliasearch-django/pull/224/files).

**Comment by PLNech** [comment]
@ercolanelli-leo: WDYT?

**Comment by julienbourdeau** [comment]
Hey, I'll be happy to open a pull request for this one 🥇

**Comment by nunomaduro** [comment]
Going to study the release process tomorrow.

**Comment by nunomaduro** [comment]
Twine is now used to deploy the version 2.
