### ISSUE TITLE
Unit test fail

### ISSUE THREAD

**Issue by apassant** [algolia/algoliasearch-client-python#31]
- Clone the current repo (2015-10-20 @ 14:00 GMT - https://github.com/algolia/algoliasearch-client-python/tree/c50a710ad90d8d0257ab4693ffb8a9b69c10af06)

- Setup the ALGOLIA_* environment variables

- Setup virtualenv and run pip install -r requirements

- Run nosetets

        [...]
        AlgoliaException: Unreachable hosts: {'8IOHDS4YN8-1.algolianet.com': 'Timeout 
        value connect was (1, 30), but it must be an int or float.', '8IOHDS4YN8
        3.algolianet.com': 'Timeout value connect was (5, 50), but it must be an int or 
        float.', '8IOHDS4YN8-2.algolianet.com': 'Timeout value connect was (3, 40), but 
        it must be an int or float.', '8IOHDS4YN8.algolia.net': 'Timeout value connect was 
        (1, 30), but it must be an int or float.'}

        ----------------------------------------------------------------------
        Ran 27 tests in 2.459s

        FAILED (errors=30)

The tests are OK with the following change in client.py, but I'm not sure that's the expected behaviour so I'm not submitying any patch here.

Replace

        for i, host in enumerate(hosts):
            if i > 1:
                if isinstance(timeout, tuple):
                    timeout = (timeout[0] + 2, timeout[1] + 10)
                    timeout = timeout[1] + 10
                else:
                    timeout += 10

By

        for i, host in enumerate(hosts):
            timeout = timeout[1] + 10

**Comment by dethi** [comment]
Can you give us the version of `requests` and `urllib3` please?
And also your system information (OS, version) ?

**Comment by apassant** [comment]
- Python2.7 on OSX 10.10.4
- requests 2.8.1
- urllib3 1.12

**Comment by Nagriar** [comment]
The requests library supports timeout with a tuple since 2.4.0:

> Support for connect timeouts! Timeout now accepts a tuple (connect, read) which is used to set individual connect and read timeouts.
https://pypi.python.org/pypi/requests/

**Comment by apassant** [comment]
My mistake - nosetests was picked from the global environment (with requests 2.2.1), not from virtualenv

Works perfectly when running ./env/bin/nosetests
