### ISSUE TITLE
algoliasearch.py present in the pip package

### ISSUE THREAD

**Issue by apassant** [algolia/algoliasearch-client-python#33]
The file algoliasearch.py is still present when installing algoliasearch via pip, while it seems deprecated as it's no longer in the git repo.

**Comment by dethi** [comment]
Hum. 
@Nagriar you should remove the dist, build and egg folder before releasing the next release

**Comment by dethi** [comment]
Thank you @apassant :)

**Comment by Nagriar** [comment]
Ok :) Thanks @apassant
