### ISSUE TITLE
algoliasearch hitsPerPage doesn't seems to work properly

### ISSUE THREAD

**Issue by Natim** [algolia/algoliasearch-client-python#365]
It seems to always use a bigger value than expected.

**Comment by Natim** [comment]
Seems related to https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/index.py#L258

**Comment by julienbourdeau** [comment]
Can you add more details about what you are doing and what's not working. Are you using the `delete
_by_query` method?

**Comment by Natim** [comment]
I am using the `index.search` method and I wanted to add some configurable pagination mecanism but without success.

**Comment by Natim** [comment]
@julienbourdeau You are right both links are not related to the search method. Sorry about the noise (must have been a bit tired).

Then I am not quite sure why, I will investigate thanks.
