### ISSUE TITLE
client.multiple_queries() mutates the queries object

### ISSUE THREAD

**Issue by Meschreiber** [algolia/algoliasearch-client-python#370]
Trying to run `client.multiple_queries()` multiple times on the same query object 

`from algoliasearch import algoliasearch
client = algoliasearch.Client(app_id, api_key)
queries = [{"query": "", "indexName": "Buff_pricing"}]
response = client.multiple_queries(queries)
response2 = client.multiple_queries(queries)`

throws the following error:

`~/.local/lib/python3.6/site-packages/algoliasearch/client.py in multiple_queries(self, queries, index_name_key, strategy)
    221         requests = []
    222         for query in queries:
--> 223             index_name = query.pop(index_name_key)
    224 
    225             requests.append({

KeyError: 'indexName'`

In order to get the index_name, we shouldn't be popping the name, no?

@PLNech suggested looking for the repercussions of this in a few places

**Comment by nunomaduro** [comment]
Hey @Meschreiber,

Thanks for reporting this issue.

This issue will be fixed in our upcoming API Client v2.

Feel free to ask me to re-open it, if you think that something is wrong.
