### ISSUE TITLE
`Index.is_task_published` broken

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-python#377]
- Algolia Client Version: 1.17.0
- Language Version: 3.5+

### Description

The method [`Index.is_task_published`](https://github.com/algolia/algoliasearch-client-python/blob/master/algoliasearch/index.py#L723-L724
) is completely broken:

1. It throws an exception:

```
Traceback (most recent call last):
  File "/home/prod/.virtualenv/perf/lib/python3.5/site-packages/algoliasearch/index.py", line 724, in is_task_published
    return self.client.wait_task(self.index_name, task_id, request_options)
  File "/home/prod/.virtualenv/perf/lib/python3.5/site-packages/algoliasearch/client.py", line 278, in wait_task
    time.sleep(time_before_retry / 1000.0)
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

... which is probably due to the fact that `request_options` is passed as a positional argument (instead of named) and overrides `time_before_retry`.

2. But anyway its semantics are inconsistent with `Client.is_task_published`. This method is not meant to wait for a task, but return immediately after the first API call.

**Comment by nunomaduro** [comment]
Hi @clement-leprovost,

The method `is_task_published` no longer exists in our Python Client v2: https://github.com/algolia/algoliasearch-client-python/pull/404.

Our API Clients v2's now implement awaitable responses. Each means people will be able todo:
```py
save_object(obj).wait();`
```

Fell free to re-open this issue, if you think that something needs to be discussed.
