### ISSUE TITLE
get_settings returns and object that cannot be used for set_settings, same for export_rules

### ISSUE THREAD

**Issue by Meschreiber** [algolia/algoliasearch-client-python#383]
- Algolia Client Version: 1.17.0
- Language Version: Python

### Description
When the user uses the get_settings() method and then tries to pass that same object to set_settings() he gets this error:

algoliasearch.helpers.AlgoliaException: numericAttributesForFiltering parameter should contain an array of string and not a string near line:1 column:300

It appears we are casting the 'null' default/None data type into a string which is not acceptable to the API.  

The same time of error appears when the user tries to export_Rules() for query rules and then send them back to the index.

`algoliasearch.helpers.AlgoliaException: Expecting a boolean (in` consequence.params.automaticFacetFilters[0].disjunctive`

This is because originally disjunctive was set to false, but the API returned the string 'False'.

### Steps To Reproduce
Use get_settings() on an index with default settings for numericAttributesForFiltering and then use the returned object in a set_settings() call

**Comment by julienbourdeau** [comment]
I'll have a look Maria, thank you 👍 

I think this should be a requirement of our API clients. `this.setSettings(this.getSettings())` should have 0 influence.

**Comment by nunomaduro** [comment]
Hey @Meschreiber,

This issue has been fixed in our upcoming API Client v2. We do have tests now to ensure that clients will be able to perform:

```py
settings = index.get_settings()
index.set_settings(settings)
```

Please ask me to re-open the issue if you think that something needs to be discussed.
