### ISSUE TITLE
[2.0] Import is broken inside docker container

### ISSUE THREAD

**Issue by LorandP** [algolia/algoliasearch-client-python#416]
- Algolia Client Version: 2.0
- Language Version: python3

### Description
I have installed using pip3 the latest algoliasearch and I have received an error regarding the import. The import could not be made.

### Steps To Reproduce

1. Install python3 on a ubuntu:18.04 inside a docker contianer
2. Install the latest algoliasearch with pip3
3. Create a python file in the same folder you have installed algoliasearch inside the docker container and import algoliasearch like 
`from algoliasearch import algoliasearch`

**Comment by nunomaduro** [comment]
@LorandP Thanks for reporting this issue.

You need to import Algolia API Client like this:

```py
from algoliasearch.search_client import SearchClient

client = SearchClient.create('YourApplicationID', 'YourAPIKey')
index = client.init_index('your_index_name')
```

**Comment by LorandP** [comment]
Thank you very much for your fast response.

**Comment by nunomaduro** [comment]
@LorandP Yesterday we released the version 2 of this library, don't hesitate to give feedback: https://discourse.algolia.com/t/python-api-client-v2-is-released/7607
