### ISSUE TITLE
Copy Index between app duplicate your synonyms

### ISSUE THREAD

**Issue by TomKlotzPro** [algolia/algoliasearch-client-python#425]
### Description
Copy index between app will duplicate synonyms.

### Steps To Reproduce
- Copy Index between app 
documentation -> [here](https://www.algolia.com/doc/api-reference/api-methods/copy-index/#copy-index-in-between-app)

### My Solution
`get_settings()` use as body parameter getVersion=2, but it should be in the `URL paramater`.

**Comment by Ant-hem** [comment]
> `get_settings()` use as body parameter getVersion=2, but it should be **in the header**.

@TomKlotzPro Please correct the description -> it should be in the `URL params` not the headers. :)

**Comment by TomKlotzPro** [comment]
Done. Thanks @Ant-hem

**Comment by nunomaduro** [comment]
Has been fixed on the `2.0.4`.
