### ISSUE TITLE
[2.x] Support for large API keys

### ISSUE THREAD

**Issue by kylegibson** [algolia/algoliasearch-client-python#462]
in #83, I implemented support for large API keys. This was published in version 1.9.2. The latest version of Algolia appears to have removed this functionality. Could it be re-added? Our implementation depends on it.

**Comment by nunomaduro** [comment]
Thanks for bringing this up to my attention. I will discuss this with my team and get back to you.

**Comment by nunomaduro** [comment]
We just added a new section on the docs, and the moment, we don't have plans on supported this: `Keep in mind that the more limitations you set, the longer the key. You might face network limitations with a key longer than 500 characters, so consider this when adding restrictions.`.
