### ISSUE TITLE
[2.x] Handle `autoGenerateObjectIDIfNotExist` parameter for `replaceAllObjects()` method

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-python#465]
The `autoGenerateObjectIDIfNotExist` boolean parameter is for now only valid in
the context of the `saveObjects()` method. As pointed out by @julienpa, it would
make sense to also accepts it as a valid parameter of `replaceAllObjects()`.

For backward-compatiblity, let's make sure the default behavior of calling
`replaceAllObjects()` without the `autoGenerateObjectIDIfNotExist` parameter is
still considered as if it was set to `false`.

**Comment by nunomaduro** [comment]
We already support this feature. The error message is not appropriated tho, needs to be fixed: 

```
algoliasearch.exceptions.MissingObjectIdException: Missing `objectID` in: {"firstname": "Jimmie", "lastname": "Barninger"}. All objects must have an unique objectID (like a primary key) to be valid. Algolia is also able to generate objectIDs automatically but *it's not recommended*. To do it, use `save_objects(objects, {'autoGenerateObjectIDIfNotExist': True}
```

**Comment by julienpa** [comment]
@nunomaduro you mean that it's possible to pass `autoGenerateObjectIDIfNotExist` to `replaceAllObjects()`?

**Comment by nunomaduro** [comment]
@julienpa Correct.

**Comment by julienpa** [comment]
So how does this work? Is it a param that can be added alongside the `safe` param?

**Comment by nunomaduro** [comment]
@julienpa The documentation is missing, but yes. You can pass both params.
