### ISSUE TITLE
If available, ensure that Analytics' regions are "us" and "de" (not "eu")

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-python#478]
We've recently discovered that at least one API client was exposing "eu" as a
valid region for the Analytics client implementation, which is wrong. Only the
following regions are available at the moment to the Analytics client:

 - "us"
 - "de"

**Comment by nunomaduro** [comment]
We don't have region enumerations on the Python client: https://github.com/algolia/algoliasearch-client-python/blob/a923a625b1e3df0aec23b18e3dca3475f0e4951d/algoliasearch/configs.py#L76.
