### ISSUE TITLE
@coroutine decorator is deprecated since python 3.8

### ISSUE THREAD

**Issue by nunomaduro** [algolia/algoliasearch-client-python#486]
This needs to be addressed soon as possible. Our current async version of the client may not be supported in Python 3.9.

**Action**: Drop decorator `@coroutine` and Python 3.4, and start using async def instead.

**Comment by nunomaduro** [comment]
Expected:

3.9.0 beta 4: Monday, 2020-06-29
3.9.0 beta 5: Monday, 2020-07-20
3.9.0 candidate 1: Monday, 2020-08-10
3.9.0 candidate 2: Monday, 2020-09-14
3.9.0 final: Monday, 2020-10-05

cc @aseure

**Comment by aseure** [comment]
Thanks for the heads-up @nunomaduro I'll try to see how and when to schedule that.

**Comment by TomKlotzPro** [comment]
No need to do a new major version for this, since after the release of python 3.9 
```This new grammar is fully backward-compatible with the existing grammar.```
https://www.python.org/dev/peps/pep-0614/#id10

**Comment by dbaty** [comment]
I think that this issue still stands: `asyncio.coroutine()` is indeed deprecated since Python 3.8. More importantly, **it will be removed in Python 3.11** (see documentation), whose final version is planned to be released on 2012-10-24 (next week).

Tested on latest Python 3.11 release candidate:

```shell
$ python --version
Python 3.11.0rc2
$ pip install aiohttp git+https://github.com/algolia/algoliasearch-client-python.git
[...]
$ python -c "import algoliasearch.search_client_async" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/damien/dl/Python-3.11.0rc2/venv/lib/python3.11/site-packages/algoliasearch/search_client_async.py", line 8, in <module>
    from algoliasearch.http.transporter_async import TransporterAsync
  File "/home/damien/dl/Python-3.11.0rc2/venv/lib/python3.11/site-packages/algoliasearch/http/transporter_async.py", line 6, in <module>
    from algoliasearch.http.requester_async import RequesterAsync
  File "/home/damien/dl/Python-3.11.0rc2/venv/lib/python3.11/site-packages/algoliasearch/http/requester_async.py", line 10, in <module>
    class RequesterAsync(Requester):
  File "/home/damien/dl/Python-3.11.0rc2/venv/lib/python3.11/site-packages/algoliasearch/http/requester_async.py", line 16, in RequesterAsync
    @asyncio.coroutine  # type: ignore
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

**Comment by dbaty** [comment]
This problem with Python 3.11 has been reported again in #549. It has more specific details and even links to a possible pull request.
