### ISSUE TITLE
Implement retry until success for restore_api_key() call in CTS test

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-python#501]
Because of the way Algolia is designed, performing a `restoreApiKey` may not
succeed because the previous `deleteApiKey` takes some time to get propagated
to all Algolia servers, giving us the following response: `[404] Key already
exists`.

To prevent that, we need to change the `testApiKeys` CTS test, if implemented,
to retry even on `[404] Key already exists` response.

**Comment by chloelbn** [comment]
CTS is not implemented in the PHP client, I'm closing this issue

**Comment by chloelbn** [comment]
Already implemented in the Python client (see https://github.com/algolia/algoliasearch-client-python/blob/master/tests/features/test_search_client.py#L254)
