### ISSUE TITLE
Feature Request: Support Places search API

### ISSUE THREAD

**Issue by sxalexander** [algolia/algoliasearch-client-python#513]
- Algolia Client Version: 2.4.0
- Language Version: Python 3.7

### Description
The python client does not yet support the Places API.  There's not a current official python implementation of this feature.

https://community.algolia.com/places/api-clients.html

### Steps To Reproduce

```
from algoliasearch.places_client import PlacesClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'algoliasearch.places_client'

```

**Comment by Haroenv** [comment]
> Places is going away on May 31st 2022. [Read our blog post announcement.](https://www.algolia.com/blog/product/sunsetting-our-places-feature/)

Thanks for your demand though!
