### ISSUE TITLE
Flake8 Linting Errors

### ISSUE THREAD

**Issue by base64** [algolia/algoliasearch-client-python#514]
- Algolia Client Version: algoliasearch-2.4.0
- Language Version: Python 3.8.5 Windows
- Flake Version: 3.8.3 (mccabe: 0.6.1, pycodestyle: 2.6.0, pyflakes: 2.2.0) CPython 3.8.3 on Windows

### Description
The Flake comments in a few places have both a type setting and the ignore flag set which causes the parameter type to be ignored.

### Steps To Reproduce
Open search_index_async.py using a Python 3.8 library and observe that line #77 has a linting error on the flake8 description of parameters on `exists_async` but not `browse_rules_async`.

![image](https://user-images.githubusercontent.com/104371/98451780-d5294b00-20fd-11eb-8b06-5e92e4a6d594.png)

I was able to resolve this warning in two ways, first by removing the #ignore flag from line #76 or by providing a acorrect return interface,

![image](https://user-images.githubusercontent.com/104371/98451807-233e4e80-20fe-11eb-8155-011dcdf07378.png)

**Comment by shortcuts** [comment]
should be good in v4
