### ISSUE TITLE
Error in json like attribute  when updating to 2.5.0

### ISSUE THREAD

**Issue by PhilipLund** [algolia/algoliasearch-client-python#527]
- Algolia Client Version: #.#.#
- Language Version:

### Description
When updating to version 2.5.0 from 2.4.0 data is missing from the searchHierachy attribute.
fetching the data using curl or looking at the Algolia dashboard shows that a product has several search hierarchies but when using the algoliasearch module version 2.5.0 only the first level is returned sometimes the first and the last level.

### Steps To Reproduce
Comparing the output of a single search between version 2.4.0 and 2.5.0

### Example
Expected response:
searchHierachy: 
{
 lvl0: [ "Husholdning" ]
 lvl1: [ "Rengøring" ]
 lvl2: [ "Rengøringsmidler" ]
 lvl3: [ "Toilet og bad" ]
 lvl4: [ "WC-rens" ]
 lvl5: [ "Toiletrens" ]
} 

Actual response:
searchHierachy: 
{
 lvl0: [ "Husholdning" ]
 lvl5: [ "Toiletrens" ]
}

**Comment by shortcuts** [comment]
Should not happen in v4
