### ISSUE TITLE
Use Secured API Key with SearchClient

### ISSUE THREAD

**Issue by nikevp** [algolia/algoliasearch-client-python#547]
- Algolia Client Version: Latest
- Language Version: Python3.8

### Description

I am trying run search queries using a secured api key with this library. It does not appear SearchClient supports passing in a read only api key. Is a read only key supported by this library?
```
client = SearchClient.create('YourApplicationID', 'YourWriteAPIKey')
```

**Comment by shortcuts** [comment]
> Is a read only key supported by this library?

Hey, the Algolia clients does not validate API keys, but forward errors from the REST API. You should be able to use any API keys, as long as the method used matches its scope
