### ISSUE TITLE
Increasing memory usage when using replace_all_objects

### ISSUE THREAD

**Issue by AugPro** [algolia/algoliasearch-client-python#557]
Hello, I have a memory issue when using [`replace_all_objects`](https://github.com/algolia/algoliasearch-client-python/blob/3bb9108d9dff627f12c921ad23dab02984f70a44/algoliasearch/search_index.py#L88). When using this function with a significant amount of documents (5 Million), I use an iterator to minimize memory consumption. 
I expect the memory usage to stay flat during the operation, however it keeps increasing. (cf image below)
![image](https://github.com/algolia/algoliasearch-client-python/assets/26441932/f4dce1bf-1cde-46e2-a199-e9936a0aa66f)

Upon investigation, it looks like the cause of this memory usage increase comes from the function `SearchIndex._chunk`, and more specifically the list `raw_responses`, which stores responses for every request sent.
https://github.com/algolia/algoliasearch-client-python/blob/3bb9108d9dff627f12c921ad23dab02984f70a44/algoliasearch/search_index.py#L505-L528 

This is a problem because the response of [`/1/indexes/{indexName}/batch`](https://www.algolia.com/doc/rest-api/search/#batch-write-operations) contains the list of `objectIDs`
```json
{
  "taskID": 792,
  "objectIDs": ["6891", "6892"]
}
```

With 5M documents, each with an objectID of ~15 characters, this accounts for **300MB**.
```python
>>> sys.getsizeof("123456789012345") * 5_000_000 / (1024**2)
305.17578125
```

Is there a request_option for the API not to return `objectIDs`, or for the code not to store them in `raw_responses` ?

Thank you 🙏

**Comment by shortcuts** [comment]
Hey there, we completely rewrote the implementation in v4, if by any chance you still use the client, could you let us know if this exists? Thanks, feel free to re-open the issue!
