### ISSUE TITLE
latest version only supports python 3.11

### ISSUE THREAD

**Issue by AjayNiven** [algolia/algoliasearch-client-python#570]
File "/home/nsroot/Projects/search/venv/lib/python3.10/site-packages/algoliasearch/search/client.py", line 16, in <module>
    from typing import Annotated, Any, Callable, Dict, List, Optional, Self, Tuple, Union
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

**Comment by shortcuts** [comment]
Hey, thanks for reporting the issue! it should be fixed in the newest version
