### ISSUE TITLE
[bug]: client close() calls transporter.close() which has been removed

### ISSUE THREAD

**Issue by martin3000** [algolia/algoliasearch-client-python#571]
### Description

client.close() calls transporter.close() which has been removed in the last release 4.4.0

### Client

Search

### Version

4.4.0

### Relevant log output

```shell
File "/home/user/.local/lib/python3.12/site-packages/algoliasearch/search/client.py", line 209, in close
    return await self._transporter.close()
                 ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Transporter' object has no attribute 'close'
```

**Comment by shortcuts** [comment]
Hey there, thanks for reporting the issue, I indeed missed that when adding the synchronous classes

Should be fixed with https://github.com/algolia/api-clients-automation/pull/3741!
