### ISSUE TITLE
Unreachable Hosts

### ISSUE THREAD

**Issue by harshmaur** [algolia/algoliasearch-client-python#72]
The new update 1.9.0 does not work properly. I get unreachable hosts error.

**Comment by ercolanelli-leo** [comment]
Hi harshmaur,

Everything is working on my side, this must be due to the setup on your side, would you mind reaching out to support@algolia.com so we can see what is wrong?

**Comment by ercolanelli-leo** [comment]
Closing for now because of a lack of info
