### ISSUE TITLE
Finding cause of too big exception

### ISSUE THREAD

**Issue by phoebebright** [algolia/algoliasearch-client-python#82]
I'm using django algolia, which calls this library and recreating an index I got this error: algoliasearch.helpers.AlgoliaException: Record at the position 464 is too big size=110956 bytes

I've been unable to find which record is causing the problem.  Neither record id 464 nor the 464th record seem large.

It would be great if the exception could display some of the data that caused the problem to make it easier to track down.

**Comment by PLNech** [comment]
Hi @phoebebright, sorry for the late reply!

I reproduced your error and checked with my colleagues working on the engine, the position given is the position of the too-big-record in the sent array, as you can see here:

```
def test_size_array(count=100, position=42, size=100000):
    arr = [0] * count
    for i in range(count):
        obj = {'objectID': i, 'v': 'foo'}
        arr[i] = obj
    arr[position] = {'objectID': 1337, 'v': 'l' * size}
    index.save_objects(arr)
```
> `algoliasearch.helpers.AlgoliaException: Record at the position 42 objectID=1337 is too big size=100021 bytes. Contact us if you need an extended quota`

As you can see here, we give any useful information we have: if the saved record bears an objectID the engine will return it in its response.
  
Please also keep in mind that you should not have a lot of records near this size, as we require that the average size of your records stays below 10KB of minified JSON: see [our FAQ entry regarding record sizes](https://www.algolia.com/doc/faq/basics/is-there-a-size-limit-for-my-index-records#faq-article) to get some advice regarding your record's size.

If this information doesn't help you track down the bad record, would you mind sending an email to support@algolia.com with more details about how you send the records? I'll be on the other side of the email 😄
