### ISSUE TITLE
use without models

### ISSUE THREAD

**Issue by rafalolszewskii** [algolia/algoliasearch-client-python#86]
Can i use Algolia without using models ? (I'am using only urls.py file for frontend side). Can I iterate somehow thru .html files or just scan every page in urls.py and then query the search using those results ?

**Comment by PLNech** [comment]
Hi @rafalolszewskii, sorry for the late reply!

From your reference to `urls.py`, I understand you are using Django. We built our [Django API Client](https://github.com/algolia/algoliasearch-django) to let you integrate quickly with Algolia by registering Django models, as you can see in the Django Client's [Quick Start Guide](https://www.algolia.com/doc/api-client/django/setup#quick-start).
However, you can also use directly this [Python API Client](https://github.com/algolia/algoliasearch-client-python): just initialise an index and you will be able to index or query it without Django models, as you can see in this client's [Getting Started Guide](https://github.com/algolia/algoliasearch-client-python#getting-started).

Let me know if this helps!

**Comment by ercolanelli-leo** [comment]
Closing as the discussion seems to be over.
